name: 🚀 Sync Blog to Profile README

on:
  push:
    branches: [main]
    paths:
      - "src/blogs/**"
      - "scripts/update-git-overview-readme.js"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout Blog Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Generate blog output
        run: npm run build:blogs

      - name: Create version output (optional)
        id: version
        run: echo "version=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Zip the blog output
        run: |
          mkdir -p zipped
          zip -r zipped/out.zip out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: out-zip
          path: zipped/out.zip

  sync-readme-to-profile:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Blog Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Download blog artifact
        uses: actions/download-artifact@v4
        with:
          name: out-zip
          path: ./out-zip

      - name: Unzip blog artifact
        run: |
          unzip -o ./out-zip/out.zip -d ./out

      - name: Clone Profile Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/Avinashgurugubelli/avinashgurugubelli.git ../profile-repo

      - name: Run README Update Script
        run: node scripts/update-git-overview-readme.js

      - name: Commit & Push to Profile Repo
        run: |
          cd ../profile-repo
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "📝 Update blog section from avi-tech-blogs v${{ needs.build.outputs.version }}" || echo "No changes to commit"
          git push
