name: Build and Publish Markdown

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'blogs/**'
      - 'scripts/**'
      - 'webpack.config.js'
      - 'src/**'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Generating the blogs build (Markdown + Webpack)
        run: npm run generate:bundle

      - name: Get version from package.json
        id: version
        run: echo "version=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT

      - name: Upload build output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: avi-blogs-v${{ steps.version.outputs.version }}
          path: out

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: version
        run: echo "version=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: avi-blogs-v${{ steps.version.outputs.version }}
          path: ./out

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          body: |
            Auto-generated release for blog version v${{ steps.version.outputs.version }}
          files: ./out/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
