name: Build and Publish Markdown

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'blogs/**'
      - 'scripts/**'
      - 'webpack.config.js'
      - 'src/**'

permissions:
  contents: write  # Required for pushing to repos and creating releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Generating the blogs build (Markdown + Webpack)
        run: npm run generate:bundle

      - name: Get version from package.json
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create ZIP of blog output
        run: |
          zip -r blog-artifacts-v${{ steps.version.outputs.version }}.zip ./out

      - name: Upload ZIP as build artifact
        uses: actions/upload-artifact@v4
        with:
          name: avi-blogs-v${{ steps.version.outputs.version }}
          path: blog-artifacts-v${{ steps.version.outputs.version }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          body: |
            Auto-generated release for blog version v${{ steps.version.outputs.version }}
          files: blog-artifacts-v${{ steps.version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sync-readme-to-profile:
    name: Sync README to Profile Repo
    runs-on: ubuntu-latest
    needs: build  # Ensure blog build is complete

    steps:
      - name: Checkout this (avi-tech-blogs) repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
      
      - name: Regenerate blog output
        run: npm run generate:bundle
      
      - name: 🔍 Debug build output directory
        run: |
          echo "Listing contents of project root"
          ls -la
          echo "Listing contents of out directory"
          ls -la out  

      - name: Clone profile repo (avinashgurugubelli)
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/Avinashgurugubelli/avinashgurugubelli.git ../profile-repo
      - name: 📁 List contents of cloned profile repo
        run: |
          echo "Target README:"
          ls -la ../profile-repo
          
      - name: Run script to update README in profile repo
        run: |
          node scripts/update-git-overview-readme.js ../profile-repo/README.md out/all-blogs-index.json
        env:
          NODE_ENV: production

      - name: Commit & Push to profile repo
        working-directory: ../profile-repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "🔄 Auto-sync blog section from avi-tech-blogs"
          git push origin main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}