name: Sync to Portfolio Website

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Copy files to temp folder
        run: |
          mkdir -p temp
          cp -r * temp/

      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: Avinashgurugubelli/my-portfolio-website
          ref: main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Copy to target repo
        run: |
          rm -rf public/blogs/system-design
          mkdir -p public/blogs/system-design
          cp -r ../temp/* public/blogs/system-design/

      - name: Commit & push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add public/blogs/system-design
          git commit -m "Auto-sync from system-design repo" || echo "No changes to commit"
          git push
